### ISSUE TITLE
Problem about paper

### ISSUE THREAD

**Issue by MrChenFeng** [DiegoOrtego/LabelNoiseMOIT#2]
Thanks so much for your work. I found that in table.6 and 7 of paper, the reported number from dividemix are much lower than the original paper, any ideas for this?

**Comment by DiegoOrtego** [comment]
Hi @MrChenFeng many thanks for your interest in our work and apologies on the delay in getting back to you.
Yes, you are right the results that we report for DivideMix differ from those they report in the paper. This is because in DivideMix paper they show in the appendix that the configuration in each dataset for different levels of noise and different noise types changes. This is tricky because the noise level (or noise ratio) and the noise type are not known in advance. Check Tab. 7 in DivideMix paper to confirm what I'm saying. So, we decided to choose the most repeated configuration by the authors in each dataset and run DivideMix. We did this to fairly compare our method and other methods which use the same configuration in each dataset. Perhaps surprisingly, we found that using the configuration that the authors report for some noise levels in other noise levels or types was not always useful, leading to worse performance.
All this is clarified in the paper. Please, see Sec 4.2 in our paper.

Best,
Diego.
